[package]
name = "server_v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["full"] }
shared_v1 = { path = "../shared_v1" }
anyhow = "1.0.71"
